version: '3'
services:
  lambda-build:
    working_dir: /app
    build: 
        context: .
        dockerfile: Dockerfile
    env_file: .env
    command: /app/deploy.sh
    volumes:
      - .:/app
  python-debug:
    image: python:3.6.1
    volumes:
      - ./dist:/app

